name: Lolwut

on:
  workflow_dispatch:
    inputs:
      lolwut:
        type: string

jobs:
  lolwut:
    runs-on: windows-latest
    steps:
    - run: |
      echo ${{ secrets.LOLWUT }}