name: Release

on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: 'Release Name'
        required: true
        type: string
      prerelease:
        description: 'Prerelease'
        required: true
        default: true
        type: boolean

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        runtime: [linux-x64, osx-x64, osx-arm64, win-x64]
        include:
          - runtime: linux-x64
            os: ubuntu-latest
          - runtime: osx-x64
            os: macos-latest
          - runtime: osx-arm64
            os: macos-latest
          - runtime: win-x64
            os: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore --runtime ${{ matrix.runtime }}
    - name: Test
      run: dotnet test --no-restore --configuration release
    - name: Build artifacts
      run: dotnet publish src/HelloWorld/HelloWorld.csproj --configuration release --self-contained true --runtime ${{ matrix.runtime }} --output dist/${{ matrix.runtime }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: helloworld-${{ github.events.inputs.releaseName }}-${{ matrix.runtime }}
        path: dist/${{ matrix.runtime }}