name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os.image }}
    strategy:
      matrix:
        os:
          - image: windows-latest
            runtime: win-x64
          - image: macos-latest
            runtime: osx-x64
          - image: ubuntu-latest
            runtime: linux-x64
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore --runtime ${{ matrix.os.runtime }}
    - name: Test
      run: dotnet test --no-restore --configuration release
    - name: Build release artifacts
      run: dotnet publish --no-restore --configuration release --self-contained true --runtime ${{ matrix.os.runtime }}